### ISSUE TITLE
バグ報告- 表示されるサムネイルが大きくなる・フォロー新着にてフォルダ毎の次ページが読み込まれない

### ISSUE THREAD

**Issue by Rsfinder** [chimaha/Pixiv-Infinite-Scroll#1]
初めまして。かねてよりpixivで自動ページ読み込みを行えるツールを探しており、
つい先日使用致しました。円滑に次ページが読み込まれており、大変重宝しています。

ただ一点、表題の通り作品が大きく表示されてしまう・フォルダではエラーとなる症状がございました。
chromium系ブラウザで使用していますが、Edgeでも同様の例が確認出来た為、
もし原因が分かる場合はご回答、修正いただけますと幸いです。

症状1：フォロー新着 pixiv.net/bookmark_new_illust.php  作品検索 pixiv.net/tags/ xxxx /artworks などで
　　　読み込まれた次のページ以降の作品サムネイルが拡大される

症状2：フォロー新着でのフォルダ別新着作品ページ pixiv.net/bookmark_new_illust.php?tag= フォルダ名
　　  　では、読み込みページがフォルダ上ではない通常の新着作品のページが表示される

環境：Brave 1.57.62 Chromium: 116.0.5845.180（Official Build）
　　　Edge  116.0.1938.76 (公式ビルド)

備考：他拡張機能、アドブロッカーによる影響は見られず

添付：症状1の実例
![GIF](https://github.com/chimaha/Pixiv-Infinite-Scroll/assets/117880432/830a2340-c247-4774-b602-54f060a3097d)

**Comment by hamachi25** [comment]
ありがとうございます。症状１は修正しました。
症状２の「フォルダ別新着作品ページ」はプレミアム機能でしょうか？その場合申し訳ないのですが、私は無料ユーザーなのでリクエストを行うURLを確認できないです...
ひとまずtagが含まれるページでは、自動で読み込みを行わないよう修正しました。

**Comment by Rsfinder** [comment]
ご対応ありがとうございます！
ただこちらの環境のせいか、アップデート後も通常表示される時もありますが、拡大される場合が多いようです。
他に要因がないか調べていきたいと思います。

フォルダ別新着作品ページはプレミアム機能です。そこまで必要性を求めている箇所ではないので、
ゆくゆく対応いただければ助かります。

他、現時点の希望としては、ユーザーアカウントページ pixiv.net/users/ xxxxxx /artworks でも
読み込みが出来るようになると申し分ございません。

お手間とならない範囲でご制作いただければ幸いです。引き続き宜しくお願いします！

**Comment by hamachi25** [comment]
イラストが拡大されるバグを再度修正しました。
[フォルダ別新着作品ページの対応版](https://github.com/chimaha/Pixiv-Infinite-Scroll/raw/main/script/pixivinfinitescroll_test.user.js)を憶測で作成したので、試してみてください。

ユーザーアカウントページもできると思います。

**Comment by Rsfinder** [comment]
早急のご対応ありがとうございます！
拡大表示バグは無くなりました。フォルダ別新着はロードされないようです。
フォルダのページ例として、

フォロー新着
https://www.pixiv.net/bookmark_new_illust.php
↓
フォロー新着 フォルダAへ移動
https://www.pixiv.net/bookmark_new_illust.php?tag=フォルダA
↓
フォロー新着 フォルダA 2p目に移動
↓
https://www.pixiv.net/bookmark_new_illust.php?p=2&tag=フォルダA

※2p以降に移動してから1p目に移動する際は、p=1となります。

上記のようなURLになります。
ただ先述のように必須仕様ではないので、お手間とならない範囲でご対応いただければ幸いです。


ユーザーアカウントページでもロードされていないようです。
同様にURL例を挙げさせていただきます

・アカウント メインページ
https://www.pixiv.net/users/11

・メインページで『すべて見る』に移動
ホーム（イラスト・マンガ） https://www.pixiv.net/users/11/artworks
イラスト https://www.pixiv.net/users/11/illustrations
マンガ https://www.pixiv.net/users/11/manga
小説 https://www.pixiv.net/users/11/novels

・2p目に移動
https://www.pixiv.net/users/11/artworks?p=2　（artworks箇所は上記同様）


急ぎご対応いただかなくとも問題ございません。お手間をいただかない範囲でご制作いただければと思います。
（こちらの環境に起因する場合もある為、問題が確認されない場合はお伝えください）

---------
また本件とはそれますが、他のpixiv用chrome拡張機能と併用できるようです。
https://chrome.google.com/webstore/detail/pixivdownloader-ex/mpeoelpkgbnhobojpafdpopjkmeodpaj
https://chrome.google.com/webstore/detail/powerful-pixiv-downloader/dkndmhgdcmjdmkdonmbgjpijejdcilfh

Pixiv-Infinite-Scrollと併せてスムーズな作品チェックが実現出来ています。本当に助かっています...！
他問題やpixivの仕様変更による弊害が出た際は報告させていただきます。重ね重ね宜しくお願い申し上げます。

**Comment by hamachi25** [comment]
詳しい情報ありがとうございます。
フォルダ別新着作品ページは現時点で対応するのは難しいです。もしできるのであれば、下記の流れにしたがってRequest URLを送ってもらえれば対応できるかもしれません。画像はFirefoxなのでブラウザによって表示は違います。

１.フォルダ別新着作品ページを開いた状態で「F12」を押してデベロッパーツールを開く
２.「Network」タブを開き、上の「XHR（Fetch/XHR）」で絞り込みを行う
３.ページを再読み込みし、左側から「illust?p=1&mode=all&lang=ja～」を探してクリック
４.右に表示される「Request URL」をコピー
![hUAsDUxfui](https://github.com/chimaha/Pixiv-Infinite-Scroll/assets/107383950/62b24a3e-ff72-4045-9b04-f6c4fede50ed)


ユーザーアカウントページはまだ未実装です。難易度が上がるので少し時間がかかります。

**Comment by Rsfinder** [comment]
三度のご対応ありがとうございます！
お伝えくださった手順より、URLを取得しました。
（tag=フォルダ名としていますが、本来のフォルダ名の例が必要であれば追記します）

`https://www.pixiv.net/ajax/follow_latest/illust?p=1&tag=フォルダ名&mode=all&lang=ja&version=e37bfd658304d5a713662bdb24fab1d00225e0a5`

誤りや追加情報が必要でしたらお伝えください。お手数をおかけしますが宜しくお願いします。

**Comment by hamachi25** [comment]
ユーザーアカウントページでの無限スクロール機能を追加しました。https://github.com/chimaha/Pixiv-Infinite-Scroll/commit/0079253a0da6148dac73521c85a058bfe6f9f2b5
フォルダ別新着作品ページは申し訳ないですが、動作しない原因が特定できないため実装できません。

**Comment by hamachi25** [comment]
最新のv1.5で、フォルダ別のフォロー新着ページに対応しました！
他に対応していないページがあったらぜひ教えてください。

**Comment by Rsfinder** [comment]
ご返答遅れ失礼しました🙇‍♂️
こちら問題なく作動しており、非常に円滑な表示になっております！有難うございます🙏

非対応ページなど、問題箇所があれば都度ご報告させていただきます。宜しくお願いします！
