### ISSUE TITLE
[Feature request] Pagination/Current page link during scrolling

### ISSUE THREAD

**Issue by puyebu** [chimaha/Pixiv-Infinite-Scroll#2]
Using userscript version.
Would it be possible to add unintrusive or optional page number somewhere between pages during scrolling?
When I scroll too much the browser becomes slower due to page size, there is no saving/continuing if the page is reloaded and this would solve the issue well enough.
For example, I scrolled to page 6 during search (https://www.pixiv.net/en/tags/scenery/artworks?mode=safe&p=6) and I want to know page number ('6' somewhere) or have a hyperlink that links to https://www.pixiv.net/en/tags/scenery/artworks?mode=safe&p=6.

**Comment by hamachi25** [comment]
I added a feature to display the number of pages currently viewed in the URL.
When the page reloads, you can view it from the page you were viewing.

**Comment by puyebu** [comment]
Thank you, works great.
