### ISSUE TITLE
ユーザー作品ページとフォローユーザーの作品ページで挙動しないエラー+α

### ISSUE THREAD

**Issue by Rsfinder** [chimaha/Pixiv-Infinite-Scroll#7]
本日辺りから起きているようです。

フォロー欄 pixiv.net/users/ xxxxxxxx /following では動いている為、
pixiv側が何らかの仕様変更を行ったかと思われます。

また本件とは別ですが、非公開フォローページでの動作も修正いただけると大変助かります。
・2p以降（ following?rest=hide&p=2 ）以降で読み込まれるページが公開フォローのページ（ following?p=2 ）

お手隙の際にご対応の程、宜しくお願い申し上げます。

**Comment by hamachi25** [comment]
ありがとうございます！修正しました！

非公開フォローページについては少しお待ち下さい。

**Comment by hamachi25** [comment]
非公開ページに対応しました！

**Comment by Rsfinder** [comment]
@chimaha ありがとうございます！非公開フォロー上でも次ページ読み込みがされることを確認できました。
フォロー欄を用いることが多々あったので大変助かります🙇‍♂️ また動作不良などありましたらご報告させていただきます。
